---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: bgd-yellow
  name: bgd-yellow
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: bgd-yellow
---
