apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: core
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./cluster-XXXX/core/
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-xxxx-gitrepo
