---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sample
  namespace: flux-system
spec:
  targetNamespace: quarkus
  install:
    createNamespace: true
  chart:
    spec:
      chart: quarkus
      version: 0.0.3
      sourceRef:
        kind: HelmRepository
        name: redhat-helm-charts
  values:
    build:
      enabled: false
    deploy:
      route:
        enabled: false
    image:
      name: quay.io/ablock/gitops-helm-quarkus
  interval: 1m0s
