apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- https://gitlab.com/christianh814/test-applicationsets/list-generator/k8s/overlays/noing-blue?ref=main

patchesJson6902:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: bgd
    path: bgd-deployment.yaml
